# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8119364e53ebf1b67643259e4e4f1a83e20a09c6095cbff14630e4befd084b2e90eddae647cf1be324d1810eb590beba3ccccb90d256b19cbcdd355f51ade9dc

test:
  secret_key_base: 4f86f22bea25f4c8744455d20141518e56f28de9e7a047f543fb0807bc38378a776e5c9b6730ee1449c242c5d22b2c7bb04c9a1590d749c68c470e03e9060f3c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
